//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public string RegNumber { get; set; }
        public string Made { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string SeatsNumber { get; set; }
        public string Transmission { get; set; }
        public string Fuel { get; set; }
        public string Color { get; set; }
        public int DailyRate { get; set; }
        public int ClassTypeID { get; set; }
    
        public virtual ClassType ClassType { get; set; }
    }
}
